---
title: "Week_13_Homework"
author: "Jacquin Moraga"
format: html
---

## Library

```{r}
#| warning: false
#| message: false

library(tidyverse)
library(here)
```


## Load Data

```{r}
#| warning: false
#| message: false

TP1 <- read_csv(here("Week_13","Data","homework","TP1.csv"))
TP2 <- read_csv(here("Week_13","Data","homework","TP2.csv"))
TP3 <- read_csv(here("Week_13","Data","homework","TP3.csv"))
TP4 <- read_csv(here("Week_13","Data","homework","TP4.csv"))
```


##Loop function

```{r}
#| warning: false
#| message: false

Oregon_path <- here("Week_13","Data","Homework") #chooses where to look in my computer

files <- dir(path = Oregon_path,pattern = ".csv") #creates a file path to my data of choice

raw_data<-read_csv(paste0(Oregon_path,"/",files[1])) #new data set

Oregon_data<-tibble(filename =  rep(NA, length(files)), 
                   mean_temp = rep(NA, length(files)),
                   mean_lux = rep(NA, length(files))) #creates the framework for the data to go into with three columns

for (i in 1:length(files)){ #starts a loop that repeats for every file
raw_data<-read_csv(paste0(Oregon_path,"/",files[i])) #reads each csv file

Oregon_data$filename[i]<-files[i] #pulls the file name from each file 
Oregon_data$mean_temp[i]<-mean(raw_data$Temp.C, na.rm =TRUE) #calcualtes the mean from each file
Oregon_data$mean_lux[i]<-mean(raw_data$Intensity.lux, na.rm =TRUE)
Oregon_data$sd_temp[i]<-sd(raw_data$Temp.C, na.rm =TRUE)
#calculates the SD of each file
Oregon_data$sd_lux[i]<-sd(raw_data$Intensity.lux, na.rm =TRUE)
}

Oregon_data
```


## Maps function

```{r}
#| warning: false
#| message: false

Oregon_path <- here("Week_13","Data","Homework") #assigning where the data is

files <- dir(path = Oregon_path, full.names = TRUE) #had to modify to full names since it wouldn't recognize files

data<-files %>% #assigning a name, using the "files" path
  set_names()%>% # sets the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% #puts everything into one data frame with ID as a column
 group_by(filename) %>% #grouping by file name
  summarise(mean_temp = mean(Temp.C, na.rm = TRUE),#calculates the mean of each
            mean_lux = mean(Intensity.lux, na.rm = TRUE),
            sd_temp = sd(Temp.C, na.rm = TRUE), #calculates the SD of each 
            sd_lux = sd(Intensity.lux, na.rm = TRUE))

data #to view the calculations
```

