---
title: "Week_09b"
format: html
---
## Library

```{r}
#| warning: false
#| message: false

library(here)
library(tidyverse)
library(forcats)

```


## Load Data

```{r}
#| warning: false
#| message: false

income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')

glimpse(starwars)

```


## Data Time

```{r}
#| warning: false
#| message: false

fruits<-factor(c("Apple", "Grape", "Banana"))
fruits

starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE)

star_counts<-starwars %>%
  filter(!is.na(species)) %>%
  mutate(species = fct_lump(species, n = 3)) %>% #lumps together speceis with less than 3 individuals is lumped into an other category
  count(species)

view(star_counts)

star_counts %>%
  ggplot(aes(x = fct_reorder(species, n), y = n))+ # reorder the factor of species by n
  geom_col()


total_income<-income_mean %>%
  group_by(year, income_quintile)%>%
  summarise(income_dollars_sum = sum(income_dollars))%>%
  mutate(income_quintile = factor(income_quintile)) # make it a factor

total_income%>%
  ggplot(aes(x = year, y = income_dollars_sum, 
             color = fct_reorder2(income_quintile,year,income_dollars_sum)))+
  geom_line()+
  labs(color = "income quantile")

starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor
  filter(n>3) %>% # only keep species that have more than 3
droplevels() %>% # drop extra levels, gets rid of everything that isn't the modified levels
  mutate(species = fct_recode(species, "Humanoid" = "Human")) #renames the levels to be what we want


starwars_clean

levels(starwars_clean$species)
```

