---
title: "Week_10a"
author: "Jacquin Moraga"
format: html
---
## Load Libraries
```{r}
#| warning: false
#| message: false

library(tidyverse)
```

## Data

```{r}
#| warning: false
#| message: false

df <- tibble(
  a = rnorm(10), # draws 10 random values from a normal distribution
  b = rnorm(10),
  c = rnorm(10),
  d = rnorm(10))


head(df)
```


## Data Time Pary WOOOOO

```{r}
#| warning: false
#| message: false

df<-df %>%
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)))

df<-df %>%
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)),
         b = (b-min(b, na.rm = TRUE))/(max(b, na.rm = TRUE)-min(b, na.rm = TRUE)),
         c = (c-min(c, na.rm = TRUE))/(max(c, na.rm = TRUE)-min(c, na.rm = TRUE)),
         d = (d-min(d, na.rm = TRUE))/(max(d, na.rm = TRUE)-min(d, na.rm = TRUE)))

head(df)
```

Lets make a function instead of doing it the long way with an equation
```{r}
#| warning: false
#| message: false

temp_C <- (temp_F - 32) * 5 / 9

fahrenheit_to_celsius <- function(temp_F) { #determines what the input is
  temp_C <- (temp_F - 32) * 5 / 9 
  return(temp_C) #determines what is being returned
}

fahrenheit_to_celsius(32) #test

C_to_K <- function(temp_C) {
  temp_K <- (temp_C + 273.15)
  return(temp_K)
}

C_to_K(20)
```

make a plot into a function
```{r}
#| warning: false
#| message: false

library(palmerpenguins)
library(PNWColors) # for the PNW color palette
# you may need to install the PNWColors library if you haven't used it yet
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 
ggplot(penguins, aes(x = body_mass_g, y = bill_length_mm, color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()

#Here is a mf graph that we want to reproduce using a function


el_penguin <- function(data = penguins, x, y, lines=TRUE) { #change the input to be other datasets, x values, and y values. Have to change in the ggplot to reflect this
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 

if(lines==TRUE){ #plot with geom_smooth
ggplot(data, aes(x = {{x}}, y = {{y}}, color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()
}
else{ #doesn't have geom_smooth
ggplot(data, aes(x = {{x}}, y = {{y}}, color = island))+
  geom_point()+
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()
}
}

#have to add the curly-curlys around the x and the y to tell it that those values are in the data set you're using

el_penguin(x = body_mass_g, y = bill_length_mm, lines = TRUE)
```

```{r}


a <- 4
b <- 5

if (a>b) { #the question
  f <- 20 #if it is true give me this number
} else {
  f <- 10 #if it is false give me this number
}

f
```

