---
title: "Week_08b"
author: "Jacquin Moraga"
format: html
---

## Load Libraries

```{r}
#| warning: false
#| message: false

library(tidyverse)
library(here)
library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
library(palmerpenguins)
```

## Plot Time

```{r}
#| warning: false
#| message: false

p1<-penguins %>%
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()



p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)

#patchwork

p1+p2 + #puts plots together side by side
  plot_layout(guides = 'collect')+ #makes only one legend
  plot_annotation(tag_levels = 'A') #labels each plot with a letter

p1/p2 #puts one plot on top of the other


#ggrepel

view(mtcars)

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # creates a text label
  geom_point(color = 'red')


#gganimate

penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   ) +
    labs(title = 'Year: {closest_state}') + #shows the year as it transitions
  anim_save(here("Week_08","output","mypengiungif.gif")) # how to save and make sure to save as a gif


#magick

penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")

penguin

penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()

ggsave(here("Week_08","Output","penguinplot.png"))

penplot<-image_read(here("Week_08","output","penguinplot.png"))

out <- image_composite(penplot, penguin, offset = "+70+30")

out

```

