---
title: "Week_06b"
author: "Jacquin Moraga"
format: html
knitr: 
  opts_chunk: 
    fig.path: "../Output/"
---
## Intro to Quarto

Today, we are learning how to work with figures.

## Load Libraries

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(kableExtra)
library(here)
library(palmerpenguins)
```

## Make a Plot

```{r}
#| warning: false
#| out-width: "70%"
#| fig-align: "center"
#| label: fig-penguin
#| fig-cap: "This is a figure showing the bill length by bill depth"
penguins %>%
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species))+
  geom_point()
```

When you look at @fig-penguin we can see that there is a positive relationship between bill length and bill depth.


```{r}
#| label: tbl-penguin
#| tbl-cap: "This is my penguin table"

penguins %>%
  group_by(species) %>%
  summarize(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% #this is a kable table
  kable_classic() %>%
  row_spec(2, bold = TRUE, color = "white", background = "red") %>%
  kable_styling(full_width = FALSE)


```

@tbl-penguin has information on the mean bill length by species.